export const INIT_ADDON = 'INIT_ADDON';
export const UPDATE_ADDON_OPTIONS = 'UPDATE_ADDON_OPTIONS';
export const RECEIVE_TRANSACTIONS = 'RECEIVE_TRANSACTIONS';
export const CATEGORIZE_TRANSACTIONS = 'CATEGORIZE_TRANSACTIONS';
export const PARSE_CATEGORIES = 'PARSE_CATEGORIES';
export const UPDATE_BUDGETING_DATA = 'UPDATE_BUDGETING_DATA';
export const SET_DATE = 'SET_DATE';
